/// Generates the API documentation.
///
///     dart run tool/doc.dart [--output <dir>]
///
/// Two things make this more than a call to `dart doc`.
///
/// The whole binding layer lives under `lib/src/`, which dartdoc treats as
/// private and will not document, and its `include` option only filters
/// libraries it already discovered rather than adding new ones. So a public
/// entry point exporting the layer is written for the duration of the run and
/// removed afterwards. It is listed in .gitignore and .pubignore as well, so
/// that a copy stranded by a hard kill can neither be committed nor shipped.
///
/// And the dartdoc bundled with the SDK -- what `dart doc` runs -- crashes on
/// this package with a RangeError inside its doc-comment handling. The version
/// pinned in dev_dependencies does not, so that is the one used here.
library;

import 'dart:io';

const String _entryPointPath = 'lib/libhegel_docs.dart';

/// Warnings dartdoc must treat as failures.
///
/// It reports a broken link or an unresolved reference and then exits zero,
/// so a gate that only checks the exit code passes on exactly the problems it
/// was added to catch -- verified before this list existed, by breaking a
/// reference and watching the build succeed. Every kind here means the
/// documentation is wrong rather than merely imperfect.
const List<String> _fatalWarnings = <String>[
  'ambiguous-doc-reference',
  'ambiguous-reexport',
  'broken-link',
  'duplicate-file',
  'invalid-parameter',
  'missing-example-file',
  'missing-example-region',
  'no-canonical-found',
  'no-documentable-libraries',
  'orphaned-file',
  'tool-error',
  'unknown-file',
  'unknown-html-fragment',
  'unknown-macro',
  'unresolved-doc-reference',
];

const String _entryPoint = '''
// TEMPORARY, GENERATED BY tool/doc.dart. If you are reading this in a
// checkout, a documentation run was killed before it could clean up; delete
// this file.
//
// The binding layer is deliberately private. This exists only so dartdoc can
// see it, and is never committed or published.
library;

export 'src/libhegel/libhegel.dart';
''';

Future<void> main(List<String> arguments) async {
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final entryPoint = File.fromUri(root.uri.resolve(_entryPointPath));

  if (entryPoint.existsSync()) {
    stderr.writeln(
      '$_entryPointPath already exists. A previous run was probably killed; '
      'delete it and try again.',
    );
    exitCode = 1;
    return;
  }

  final output = _argumentValue(arguments, '--output') ?? 'build/doc';

  // Emptied first. dartdoc overwrites what it regenerates but leaves behind
  // pages for anything since renamed or removed, so a stale directory keeps
  // serving documentation for API that no longer exists.
  final outputDirectory = Directory.fromUri(root.uri.resolve(output));
  if (outputDirectory.existsSync()) {
    outputDirectory.deleteSync(recursive: true);
  }

  entryPoint.writeAsStringSync(_entryPoint);
  try {
    final result = await Process.start(
      Platform.resolvedExecutable,
      <String>[
        'run',
        'dartdoc',
        '--output',
        output,
        '--validate-links',
        '--errors',
        _fatalWarnings.join(','),
      ],
      workingDirectory: root.path,
      mode: ProcessStartMode.inheritStdio,
    );
    exitCode = await result.exitCode;
  } finally {
    // Always, including when dartdoc fails: leaving it behind would turn the
    // private layer into public API on the next publish.
    if (entryPoint.existsSync()) entryPoint.deleteSync();
  }

  if (exitCode == 0) {
    stdout.writeln('documentation written to $output');
  }
}

String? _argumentValue(List<String> arguments, String name) {
  final index = arguments.indexOf(name);
  if (index >= 0 && index + 1 < arguments.length) return arguments[index + 1];
  for (final argument in arguments) {
    if (argument.startsWith('$name=')) {
      return argument.substring(name.length + 1);
    }
  }
  return null;
}
