/// Generates the API documentation.
///
///     dart run tool/doc.dart [--output <dir>]
///
/// Two things make this more than a call to `dart doc`.
///
/// The whole binding layer lives under `lib/src/`, which dartdoc treats as
/// private and will not document, and its `include` option only filters
/// libraries it already discovered rather than adding new ones. So a public
/// entry point exporting the layer is written for the duration of the run and
/// removed afterwards. It is listed in .gitignore and .pubignore as well, so
/// that a copy stranded by a hard kill can neither be committed nor shipped.
///
/// And the dartdoc bundled with the SDK -- what `dart doc` runs -- crashes on
/// this package with a RangeError inside its doc-comment handling. The version
/// pinned in dev_dependencies does not, so that is the one used here.
library;

import 'dart:io';

import 'package:path/path.dart' as p;

const String _entryPointPath = 'lib/libhegel_docs.dart';

/// Warnings dartdoc must treat as failures.
///
/// It reports a broken link or an unresolved reference and then exits zero,
/// so a gate that only checks the exit code passes on exactly the problems it
/// was added to catch -- verified before this list existed, by breaking a
/// reference and watching the build succeed.
///
/// This is every kind dartdoc 9.0.9 defines, except `type-as-html`, which
/// that version has deprecated and complains about being asked for. Listing
/// them all is deliberate: the previous list was chosen by judgement and
/// left out
/// `internal-error` and `missing-from-search-index`, both of which mean
/// generation itself went wrong and both of which dartdoc reports as mere
/// warnings, so the gate would announce success over them.
///
/// dartdoc does not validate these names -- an invented one is accepted in
/// silence -- so nothing here can catch a typo or a name dropped by a later
/// release. That is why `dartdoc` is pinned to an exact version in
/// pubspec.yaml rather than a range, and why bumping it means regenerating
/// this list from that version's `PackageWarning` enum.
const List<String> _fatalWarnings = <String>[
  'ambiguous-doc-reference',
  'ambiguous-reexport',
  'broken-link',
  'category-order-gives-missing-package-name',
  'deprecated',
  'duplicate-file',
  'ignored-canonical-for',
  'internal-error',
  'invalid-parameter',
  'missing-example-file',
  'missing-example-region',
  'missing-from-search-index',
  'no-canonical-found',
  'no-documentable-libraries',
  'no-library-level-docs',
  'orphaned-file',
  'tool-error',
  'unknown-file',
  'unknown-html-fragment',
  'unknown-macro',
  'unresolved-doc-reference',
];

const String _entryPoint = '''
// TEMPORARY, GENERATED BY tool/doc.dart. If you are reading this in a
// checkout, a documentation run was killed before it could clean up; delete
// this file.
//
// The binding layer is deliberately private. This exists only so dartdoc can
// see it, and is never committed or published.
library;

export 'src/libhegel/libhegel.dart';
''';

/// Written into the output directory once a run succeeds, and the only thing
/// that makes a non-empty directory safe to empty on a later run.
///
/// It used to be `index.json`, on the reasoning that dartdoc always writes
/// one. But plenty of unrelated directories contain an `index.json` -- web
/// roots, data dumps -- and treating one as proof of ownership meant
/// `--output some/web/dir` would delete somebody's work. Recognising output
/// that looks like ours is not the same as recognising output that is ours,
/// so this file is ours and nothing else claims it.
///
/// It cannot be written before dartdoc runs: `unknown-file` is one of the
/// warnings we make fatal, and dartdoc counts anything in the tree it did not
/// write, dotfiles included.
const String _ownershipMarker = '.hegel-doc-output';

/// Resolves [value] against [root] using filesystem rules.
///
/// Not URI resolution: `Uri.resolve` reads a Windows path like `C:\docs` as a
/// URI with scheme `c`, and a UNC path as a host, so both are rejected before
/// dartdoc ever runs.
Directory resolveOutputDirectory(Directory root, String value) {
  if (value.trim().isEmpty) {
    throw ArgumentError.value(value, '--output', 'must not be empty');
  }
  // Separators are normalised so that a value written with forward slashes
  // still compares against paths built with the platform's separator.
  final normalised = Platform.isWindows ? value.replaceAll('/', r'\') : value;
  final given = Directory(normalised);
  return given.isAbsolute
      ? given
      : Directory('${root.path}${Platform.pathSeparator}$normalised');
}

/// [path] with `.` and `..` collapsed, made absolute, and case-folded where
/// the platform ignores case.
///
/// Purely lexical, so it works on a directory that does not exist yet. That
/// is what the physical form below cannot do, and why both are needed:
/// `--output missing/../lib` names lib the moment the operating system
/// resolves it, but every character comparison against "lib" misses.
String lexicalPath(String path) => p.canonicalize(path);

/// The path the operating system will actually use, symlinks resolved.
///
/// Only answerable once the directory exists, which is why [prepareOutput]
/// creates it before the checks run.
String physicalPath(Directory directory) =>
    p.canonicalize(directory.resolveSymbolicLinksSync());

/// Creates [output] and every missing directory above it, returning the ones
/// it had to make so a refusal can undo them.
///
/// Creating a directory is cheap and reversible; deleting one is neither,
/// which is the whole reason the order runs this way round. Resolving
/// symlinks is the only way to learn the path dartdoc will really write to,
/// and it only works on something that is already there.
List<Directory> prepareOutput(Directory output) {
  final created = <Directory>[];
  var probe = output.absolute;
  while (!probe.existsSync()) {
    created.insert(0, probe);
    final parent = probe.parent;
    if (parent.path == probe.path) break;
    probe = parent;
  }
  output.createSync(recursive: true);
  return created;
}

/// Removes the directories [prepareOutput] made, innermost first, stopping at
/// the first that is not empty.
void undoPrepare(List<Directory> created) {
  for (final directory in created.reversed) {
    if (!directory.existsSync()) continue;
    if (directory.listSync().isNotEmpty) return;
    directory.deleteSync();
  }
}

void _refuseIfRelated(String display, String base, String target) {
  final separator = Platform.pathSeparator;
  if (target == base) {
    throw ArgumentError.value(display, '--output', 'is the package itself');
  }
  if ('$base$separator'.startsWith('$target$separator')) {
    throw ArgumentError.value(display, '--output', 'contains the package');
  }
  for (final protected in <String>['lib', 'test', 'tool', 'hook', '.git']) {
    final reserved = '$base$separator$protected';
    if (target == reserved || target.startsWith('$reserved$separator')) {
      throw ArgumentError.value(display, '--output', 'is inside $protected');
    }
  }
}

/// Throws unless [output] is a directory this tool may empty.
///
/// The check exists because emptying it is destructive and the path comes
/// from an argument. Before it, `--output .` erased the checkout including
/// .git, and `--output ..` erased everything beside it.
///
/// Every lexical and physical form of both paths is compared against every
/// form of the other, because each of the two holes found so far lived in a
/// gap between one form and another: a symlinked package root, and dot
/// segments in a suffix that did not exist yet. Comparing one pair is what
/// let each of them through.
void checkSafeToEmpty(Directory root, Directory output) {
  final bases = <String>{lexicalPath(root.path)};
  if (root.existsSync()) bases.add(physicalPath(root));
  final targets = <String>{lexicalPath(output.path)};
  if (output.existsSync()) targets.add(physicalPath(output));

  for (final base in bases) {
    for (final target in targets) {
      _refuseIfRelated(output.path, base, target);
    }
  }

  final marker = File(
    '${output.path}${Platform.pathSeparator}$_ownershipMarker',
  );
  if (output.existsSync() &&
      !marker.existsSync() &&
      output.listSync().isNotEmpty) {
    throw ArgumentError.value(
      output.path,
      '--output',
      'is not empty and this tool did not write it. Delete it by hand if it '
          'really is a documentation directory -- output from before this '
          'check existed carries no marker and is refused once, on purpose',
    );
  }
}

Future<void> main(List<String> arguments) async {
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final entryPoint = File.fromUri(root.uri.resolve(_entryPointPath));

  if (entryPoint.existsSync()) {
    stderr.writeln(
      '$_entryPointPath already exists. A previous run was probably killed; '
      'delete it and try again.',
    );
    exitCode = 1;
    return;
  }

  final output = _argumentValue(arguments, '--output') ?? 'build/doc';

  // Emptied first. dartdoc overwrites what it regenerates but leaves behind
  // pages for anything since renamed or removed, so a stale directory keeps
  // serving documentation for API that no longer exists. Emptying is
  // destructive and the path is an argument, so it is checked first.
  final Directory outputDirectory;
  List<Directory> created = <Directory>[];
  try {
    // Collapsed before anything is created, so that a path written with dot
    // segments creates the directory it actually names and not the ones it
    // spells on the way there.
    outputDirectory = Directory(
      lexicalPath(resolveOutputDirectory(root, output).path),
    );
    created = prepareOutput(outputDirectory);
    checkSafeToEmpty(root, outputDirectory);
  } on ArgumentError catch (error) {
    undoPrepare(created);
    stderr.writeln(
      'refusing to write documentation to ${error.invalidValue}: '
      '${error.message}',
    );
    exitCode = 1;
    return;
  }
  if (outputDirectory.existsSync()) {
    outputDirectory.deleteSync(recursive: true);
  }

  entryPoint.writeAsStringSync(_entryPoint);
  try {
    final result = await Process.start(
      Platform.resolvedExecutable,
      <String>[
        'run',
        'dartdoc',
        '--output',
        outputDirectory.path,
        '--validate-links',
        '--errors',
        _fatalWarnings.join(','),
      ],
      workingDirectory: root.path,
      mode: ProcessStartMode.inheritStdio,
    );
    exitCode = await result.exitCode;
  } finally {
    // Always, including when dartdoc fails: leaving it behind would turn the
    // private layer into public API on the next publish.
    if (entryPoint.existsSync()) entryPoint.deleteSync();
  }

  if (exitCode == 0) {
    outputDirectory.createSync(recursive: true);
    File(
      '${outputDirectory.path}${Platform.pathSeparator}$_ownershipMarker',
    ).writeAsStringSync(
      'Written by tool/doc.dart. Its presence is what allows a later run to '
      'empty this directory; delete it and the tool will refuse to touch '
      'anything already here.\n',
    );
    stdout.writeln('documentation written to $output');
  } else {
    // Everything here was written by the run that just failed -- the
    // directory was emptied on the way in -- so clearing it leaves no
    // half-generated tree for the next run to refuse to empty.
    if (outputDirectory.existsSync()) {
      outputDirectory.deleteSync(recursive: true);
    }
  }
}

String? _argumentValue(List<String> arguments, String name) {
  final index = arguments.indexOf(name);
  if (index >= 0 && index + 1 < arguments.length) return arguments[index + 1];
  for (final argument in arguments) {
    if (argument.startsWith('$name=')) {
      return argument.substring(name.length + 1);
    }
  }
  return null;
}
