/// Generates the API documentation.
///
///     dart run tool/doc.dart [--output <dir>]
///
/// Two things make this more than a call to `dart doc`.
///
/// The whole binding layer lives under `lib/src/`, which dartdoc treats as
/// private and will not document, and its `include` option only filters
/// libraries it already discovered rather than adding new ones. So a public
/// entry point exporting the layer is written for the duration of the run and
/// removed afterwards. It is listed in .gitignore and .pubignore as well, so
/// that a copy stranded by a hard kill can neither be committed nor shipped.
///
/// And the dartdoc bundled with the SDK -- what `dart doc` runs -- crashes on
/// this package with a RangeError inside its doc-comment handling. The version
/// pinned in dev_dependencies does not, so that is the one used here.
library;

import 'dart:io';

const String _entryPointPath = 'lib/libhegel_docs.dart';

/// Warnings dartdoc must treat as failures.
///
/// It reports a broken link or an unresolved reference and then exits zero,
/// so a gate that only checks the exit code passes on exactly the problems it
/// was added to catch -- verified before this list existed, by breaking a
/// reference and watching the build succeed.
///
/// This is every kind dartdoc 9.0.9 defines, except `type-as-html`, which
/// that version has deprecated and complains about being asked for. Listing
/// them all is deliberate: the previous list was chosen by judgement and
/// left out
/// `internal-error` and `missing-from-search-index`, both of which mean
/// generation itself went wrong and both of which dartdoc reports as mere
/// warnings, so the gate would announce success over them.
///
/// dartdoc does not validate these names -- an invented one is accepted in
/// silence -- so nothing here can catch a typo or a name dropped by a later
/// release. That is why `dartdoc` is pinned to an exact version in
/// pubspec.yaml rather than a range, and why bumping it means regenerating
/// this list from that version's `PackageWarning` enum.
const List<String> _fatalWarnings = <String>[
  'ambiguous-doc-reference',
  'ambiguous-reexport',
  'broken-link',
  'category-order-gives-missing-package-name',
  'deprecated',
  'duplicate-file',
  'ignored-canonical-for',
  'internal-error',
  'invalid-parameter',
  'missing-example-file',
  'missing-example-region',
  'missing-from-search-index',
  'no-canonical-found',
  'no-documentable-libraries',
  'no-library-level-docs',
  'orphaned-file',
  'tool-error',
  'unknown-file',
  'unknown-html-fragment',
  'unknown-macro',
  'unresolved-doc-reference',
];

const String _entryPoint = '''
// TEMPORARY, GENERATED BY tool/doc.dart. If you are reading this in a
// checkout, a documentation run was killed before it could clean up; delete
// this file.
//
// The binding layer is deliberately private. This exists only so dartdoc can
// see it, and is never committed or published.
library;

export 'src/libhegel/libhegel.dart';
''';

/// A file dartdoc always writes, used to recognise its own output.
///
/// Emptying a directory is only safe if we are sure we made it.
const String _dartdocMarker = 'index.json';

/// Resolves [value] against [root] using filesystem rules.
///
/// Not URI resolution: `Uri.resolve` reads a Windows path like `C:\docs` as a
/// URI with scheme `c`, and a UNC path as a host, so both are rejected before
/// dartdoc ever runs.
Directory resolveOutputDirectory(Directory root, String value) {
  if (value.trim().isEmpty) {
    throw ArgumentError.value(value, '--output', 'must not be empty');
  }
  // Separators are normalised so that a value written with forward slashes
  // still compares against paths built with the platform's separator.
  final normalised = Platform.isWindows ? value.replaceAll('/', r'\') : value;
  final given = Directory(normalised);
  return given.isAbsolute
      ? given
      : Directory('${root.path}${Platform.pathSeparator}$normalised');
}

/// The canonical form of [path], symlinks resolved, whether or not it exists.
///
/// `resolveSymbolicLinksSync` only works on something that is already there,
/// so a directory yet to be created would stay unresolved while the package
/// root does not. On macOS, where the temporary directory is reached through
/// a symlink, the two then never compare equal and every check below passes
/// silently -- which is exactly how `--output lib/nested` slipped through.
String canonicalPath(String path) {
  final separator = Platform.pathSeparator;
  var directory = Directory(path).absolute;
  final missing = <String>[];
  while (!directory.existsSync()) {
    final parent = directory.parent;
    if (parent.path == directory.path) break;
    missing.insert(
      0,
      directory.path
          .substring(parent.path.length)
          .replaceAll(RegExp(r'^[\\/]+'), ''),
    );
    directory = parent;
  }
  final resolved = directory.existsSync()
      ? directory.resolveSymbolicLinksSync()
      : directory.path;
  return <String>[resolved, ...missing].join(separator);
}

/// Throws unless [output] is a directory this tool may empty.
///
/// The check exists because emptying it is destructive and the path comes
/// from an argument. Before this, `--output .` erased the checkout including
/// .git, and `--output ..` erased everything beside it.
void checkSafeToEmpty(Directory root, Directory output) {
  final target = canonicalPath(output.path);
  final base = canonicalPath(root.path);
  final separator = Platform.pathSeparator;

  if (target == base) {
    throw ArgumentError.value(output.path, '--output', 'is the package itself');
  }
  if (!'$base$separator'.startsWith('$target$separator')) {
    // Not an ancestor of the package: fine so far.
  } else {
    throw ArgumentError.value(output.path, '--output', 'contains the package');
  }
  for (final protected in <String>['lib', 'test', 'tool', 'hook', '.git']) {
    final reserved = '$base$separator$protected';
    if (target == reserved || target.startsWith('$reserved$separator')) {
      throw ArgumentError.value(
        output.path,
        '--output',
        'is inside $protected',
      );
    }
  }

  final marker = File('${output.path}$separator$_dartdocMarker');
  if (output.existsSync() &&
      !marker.existsSync() &&
      output.listSync().isNotEmpty) {
    throw ArgumentError.value(
      output.path,
      '--output',
      'is not empty and was not written by dartdoc; remove it by hand if it '
          'really is a documentation directory',
    );
  }
}

Future<void> main(List<String> arguments) async {
  final root = Directory.fromUri(Platform.script.resolve('../'));
  final entryPoint = File.fromUri(root.uri.resolve(_entryPointPath));

  if (entryPoint.existsSync()) {
    stderr.writeln(
      '$_entryPointPath already exists. A previous run was probably killed; '
      'delete it and try again.',
    );
    exitCode = 1;
    return;
  }

  final output = _argumentValue(arguments, '--output') ?? 'build/doc';

  // Emptied first. dartdoc overwrites what it regenerates but leaves behind
  // pages for anything since renamed or removed, so a stale directory keeps
  // serving documentation for API that no longer exists. Emptying is
  // destructive and the path is an argument, so it is checked first.
  final Directory outputDirectory;
  try {
    outputDirectory = resolveOutputDirectory(root, output);
    checkSafeToEmpty(root, outputDirectory);
  } on ArgumentError catch (error) {
    stderr.writeln('refusing to write documentation there: ${error.message}');
    exitCode = 1;
    return;
  }
  if (outputDirectory.existsSync()) {
    outputDirectory.deleteSync(recursive: true);
  }

  entryPoint.writeAsStringSync(_entryPoint);
  try {
    final result = await Process.start(
      Platform.resolvedExecutable,
      <String>[
        'run',
        'dartdoc',
        '--output',
        outputDirectory.path,
        '--validate-links',
        '--errors',
        _fatalWarnings.join(','),
      ],
      workingDirectory: root.path,
      mode: ProcessStartMode.inheritStdio,
    );
    exitCode = await result.exitCode;
  } finally {
    // Always, including when dartdoc fails: leaving it behind would turn the
    // private layer into public API on the next publish.
    if (entryPoint.existsSync()) entryPoint.deleteSync();
  }

  if (exitCode == 0) {
    stdout.writeln('documentation written to $output');
  }
}

String? _argumentValue(List<String> arguments, String name) {
  final index = arguments.indexOf(name);
  if (index >= 0 && index + 1 < arguments.length) return arguments[index + 1];
  for (final argument in arguments) {
    if (argument.startsWith('$name=')) {
      return argument.substring(name.length + 1);
    }
  }
  return null;
}
